packages:
  - "apps/*"
  - "apps/IMS/*"
  - "packages/*"
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@swc/core"
  - "esbuild"
  - "msgpackr-extract"
  - "sharp"
  - "unrs-resolver"
